### ISSUE TITLE
Releases don't include details about the changes or bugfixes

### ISSUE THREAD

**Issue by CZEMacLeod** [madskristensen/SqlFormatter#5]
I'm subscribe to the released for this repo, but it is unclear what is in each release as there are no related issues or a list of commits associated.

At a minimum, an autogenerated list of issues closed, PRs and direct commits would make it easy to work out if anything significant has changed and if I need to download an update.

Currently, I just have to go to the repo history and look at the commit messages.

**Comment by madskristensen** [comment]
Do you know of any GitHub Actions tricks I can use for that. It would be cool, but I don't really want to do this manually

**Comment by CZEMacLeod** [comment]
Not for gha - I use azure devops myself and the [GitHubRelease@1](https://learn.microsoft.com/en-gb/azure/devops/pipelines/tasks/reference/github-release-v1?view=azure-pipelines) action.
I assume there is an equivalent for gha - it is pretty much the same thing.

```yaml
- powershell: |
    Write-Host "Tagging Build: $env:BuildNumber"
    $tag = "v" + $env:BuildNumber
    git tag $tag
    git push origin $tag
  displayName: Tag build
  env:
    BuildNumber: $(Build.BuildNumber)
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))


- task: GithubRelease@0 
  displayName: 'Create GitHub Release'
  condition: and(succeeded(), ne(variables['package_count'],0))
  inputs:
    gitHubConnection: github-czemacleod
    repositoryName: CZEMacLeod/C3D.Extensions.Playwright.AspNetCore
    assets: $(Build.ArtifactStagingDirectory)/*.nupkg
    addChangeLog: true
```
[azure-pipelines.yml](https://github.com/CZEMacLeod/C3D.Extensions.Playwright.AspNetCore/blob/2b765c00e1175ebd01e519cbdc109f774f04e19f/build/azure-pipelines.yml#L307C1-L324C23)

and the example output:

[C3D.Extensions.Playwright.AspNetCore v0.1.40](https://github.com/CZEMacLeod/C3D.Extensions.Playwright.AspNetCore/releases/tag/v0.1.40)

**Comment by CZEMacLeod** [comment]
Looks like your task `softprops/action-gh-release@v2` supports this.
https://github.com/softprops/action-gh-release?tab=readme-ov-file#-customizing

I think you add the option `generate_release_notes` with the value true to the inputs of the task.

https://github.com/madskristensen/SqlFormatter/blob/376acdcb60c5ac7e1808492348ec767ab7d974d9/.github/workflows/build.yaml#L79-L87

```yaml
      - name: Tag and release
        if: ${{ github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '[release]') }}
        id: tag_release
        uses: softprops/action-gh-release@v2
        with:
          body: '# Release ${{ needs.build.outputs.version }}'
          generate_release_notes: true
          tag_name: ${{ needs.build.outputs.version }}
          files: |
            **/*.vsix
```

You might need to follow these instructions to customize the release notes:
https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
